---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: veleroinstalls.managed.openshift.io
spec:
  group: managed.openshift.io
  names:
    kind: VeleroInstall
    listKind: VeleroInstallList
    plural: veleroinstalls
    singular: veleroinstall
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the storage bucket
      jsonPath: .status.storageBucket.name
      name: Bucket
      type: string
    - description: Has the storage bucket been successfully provisioned
      jsonPath: .status.storageBucket.provisioned
      name: Provisioned
      type: boolean
    - jsonPath: .status.storageBucket.lastSyncTimestamp
      name: Last Sync
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: VeleroInstall is the Schema for the veleroinstalls API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VeleroInstallSpec defines the desired state of Velero
            type: object
          status:
            description: VeleroInstallStatus defines the observed state of Velero
            properties:
              storageBucket:
                description: StorageBucket contains details of the storage bucket
                  for backups
                properties:
                  lastSyncTimestamp:
                    description: LastSyncTimestamp is the time that the bucket policy
                      was last synced.
                    format: date-time
                    type: string
                  name:
                    description: Name is the name of the storage bucket created to
                      store Velero backup details
                    maxLength: 63
                    type: string
                  provisioned:
                    description: Provisioned is true once the bucket has been initially
                      provisioned.
                    type: boolean
                required:
                - provisioned
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
