apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: managed-velero-operator-0.0.1
  namespace: openshift-velero
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: Operator to manage installation of Velero for OpenShift Clusters.
    containerImage: quay.io/app-sre/managed-velero-operator:latest
    createdAt: "2019-04-10T17:34:33Z"
    support: Red Hat OpenShift SRE
spec:
  displayName: managed-velero-operator
  description: Operator to manage installation of Velero for OpenShift Clusters.
  keywords:
  - kubernetes
  - backup
  - openshift
  - cluster
  - velero
  - storage
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions: []
      permissions: []
  customresourcedefinitions:
    owned:
